name: fullstack_cli
description: Interactive CLI for fullstack service
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.7.0
  args: ^2.6.0
  io: ^1.0.4
  path: ^1.9.0
  json_annotation: ^4.9.0
  ansicolor: ^2.0.3

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  lints: ^5.1.1
